
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-cli: circleci/aws-cli@1.4.0
  aws-eks: circleci/aws-eks@1.0.3
  ci: matic/orb-common@0.2
  ruby: circleci/ruby@1.8.0

jobs:

  rspec-test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
      - image: vault
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: vault_root_token
          SKIP_SETCAP: true
      - image: postgres:14.1-alpine
        environment:
          POSTGRES_USER: 'vault_root'
          POSTGRES_PASSWORD: 'root_password'
          POSTGRES_DB: 'app_db'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up vault
          command: bash local/vault/setup.sh
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec
      - store_test_results:
          path: reports/rspec
      - store_artifacts:
          path: reports/rspec
      - ci/slack-stage-message

  rubocop:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

workflows:

  settings_reader-vault_resolver.build-pull-request:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:

      - rspec-test:
          name: Rspec-test
          context: global
          matrix:
            parameters:
              ruby-version: [ '2.5', '2.6', '2.7', '3.0' ]

      - rubocop:
          name: Rubocop
          context: global
