
version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0

jobs:

  rspec-test:
    resource_class: small
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
        environment:
          COVERAGE: true
          CODECOV_TOKEN: a0c859b6-dfb7-4d9f-9933-2dd945cdd960
          VAULT_ADDR: 'http://127.0.0.1:8200'
          VAULT_TOKEN: 'vault_root_token'
      - image: vault
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: vault_root_token
          SKIP_SETCAP: true
      - image: postgres:14.1-alpine
        environment:
          POSTGRES_DB: 'app_db'
          POSTGRES_USER: 'vault_root'
          POSTGRES_PASSWORD: 'root_password'
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up vault
          command: sh local/vault/setup.sh
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec
      - store_test_results:
          path: reports/rspec
      - store_artifacts:
          path: reports/rspec
      - ci/slack-stage-message

  rubocop:
    resource_class: small
    docker:
      - image: cimg/ruby:2.5
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel

  release:
    parameters:
      tag:
        type: string
        default: "default-tag"
    docker:
      - image: cimg/ruby:2.7.5
    environment:
      RELEASE_TAG: << parameters.tag >>
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up credentials
          command: |
              mkdir -p $HOME/.gem
              touch $HOME/.gem/credentials
              chmod 0600 $HOME/.gem/credentials
              printf -- "---\n:rubygems_api_key: $RUBYGEMS_API_KEY\n" > $HOME/.gem/credentials
      - run:
          name: Set version
          command: sed -i "s/[[:digit:]].[[:digit:]].[[:digit:]]/${RELEASE_TAG}/g" $(find . -name "version.rb")
      - run:
          name: Build gem
          command: gem build *.gemspec
      - run:
          name: Push gem
          command: gem push *.gem

workflows:

  settings_reader-vault_resolver.build-pull-request:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:

      - rspec-test:
          context: global
          matrix:
            parameters:
              ruby-version: [ '2.5', '2.6', '2.7', '3.0' ]

      - rubocop:
          name: Rubocop
          context: global

  settings_reader-vault_resolver.release:
    jobs:

      - release:
          tag: << pipeline.git.tag >>
          context: gem-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d\.\d\.\d/ # It should be [digin dot digit dot digit] format
