name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    env:
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_TOKEN: 'vault_root_token'
      DATABASE_ADDR: 'database'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.3' ]
#    services:
#      vault:
#        image: hashicorp/vault
#        ports:
#          - "8200:8200"
#        env:
#          VAULT_DEV_ROOT_TOKEN_ID: vault_root_token
#          SKIP_SETCAP: true
#      database:
#        image: postgres:14.1-alpine
#        ports:
#          - "5432:5432"
#        env:
#          POSTGRES_USER: 'vault_root'
#          POSTGRES_PASSWORD: 'root_password'
#          POSTGRES_DB: 'app_db'
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#      aws:
#        image: localstack/localstack
#        ports:
#          - "127.0.0.1:4566:4566"            # LocalStack Gateway
#          - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#        env:
#          DEBUG: 0
#        volumes:
#          - '/home/runner/work/settings_reader-vault_resolver/local/localstack/app-access-policy.json:/etc/localstack/init/ready.d/app-access-policy.json'
#          - '/home/runner/work/settings_reader-vault_resolver/local/localstack/app-assume-policy.json:/etc/localstack/init/ready.d/app-assume-policy.json'
#          - '/home/runner/work/settings_reader-vault_resolver/local/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Start Dependencies
        run: |
          docker-compose up -d
          echo "Waiting 15 seconds for initial configuraiton"
          sleep 15

      - name: Run specs
        env:
          COVERAGE: true
        run: bundle exec rspec

      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Set up credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}\n" > $HOME/.gem/credentials

      - name: Get version
        run: echo "${GITHUB_REF/refs\/tags\//}" > release.tag
      - name: Set version
        run: sed -i "s/0.0.0/$(<release.tag)/g" $(find . -name "version.rb")

      - name: Build gem
        run: gem build *.gemspec
      - name: Push gem
        run: gem push *.gem