name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Set up Bundler
        run: gem install bundler:2.1.4
      - name: Set up credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}\n" > $HOME/.gem/credentials

      - name: Get version
        run: echo "${GITHUB_REF/refs\/tags\//}" > release.tag
      - name: Set version
        run: sed -i "s/0.0.0/$(<release.tag)/g" $(find . -name "version.rb")

      - name: Build gem
        run: gem build *.gemspec
      - name: Push gem
        run: gem push *.gem